[2024-08-21 19:13:16,861] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: captors_dag.task_4 2024-08-21T19:05:47.227767+00:00 [queued]>
[2024-08-21 19:13:16,897] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: captors_dag.task_4 2024-08-21T19:05:47.227767+00:00 [queued]>
[2024-08-21 19:13:16,898] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-08-21 19:13:16,898] {taskinstance.py:1043} INFO - Starting attempt 2 of 3
[2024-08-21 19:13:16,899] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-08-21 19:13:16,908] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): task_4> on 2024-08-21T19:05:47.227767+00:00
[2024-08-21 19:13:16,912] {standard_task_runner.py:52} INFO - Started process 57 to run task
[2024-08-21 19:13:16,916] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'captors_dag', 'task_4', '2024-08-21T19:05:47.227767+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/mod_captors.py', '--cfg-path', '/tmp/tmpui09qbtq', '--error-file', '/tmp/tmp0zd56c_o']
[2024-08-21 19:13:16,917] {standard_task_runner.py:77} INFO - Job 9: Subtask task_4
[2024-08-21 19:13:16,959] {logging_mixin.py:104} INFO - Running <TaskInstance: captors_dag.task_4 2024-08-21T19:05:47.227767+00:00 [running]> on host ad333fe07a6a
[2024-08-21 19:13:17,005] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=captors_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2024-08-21T19:05:47.227767+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-21T19:05:47.227767+00:00
[2024-08-21 19:13:17,016] {python.py:118} INFO - Done. Returned value was: None
[2024-08-21 19:13:17,030] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=captors_dag, task_id=task_4, execution_date=20240821T190547, start_date=20240821T191316, end_date=20240821T191317
[2024-08-21 19:13:17,062] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21 19:13:17,090] {local_task_job.py:146} INFO - Task exited with return code 0
